/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as PortalIndexRouteImport } from './routes/_portal/index'
import { Route as PortalApprovalsRouteImport } from './routes/_portal/approvals'
import { Route as PortalAuditRouteImport } from './routes/_portal/audit'
import { Route as PortalBackfillsRouteImport } from './routes/_portal/backfills'
import { Route as PortalCostRouteImport } from './routes/_portal/cost'
import { Route as PortalEvalsRouteImport } from './routes/_portal/evals'
import { Route as PortalHealthRouteImport } from './routes/_portal/health'
import { Route as PortalMemoryRouteImport } from './routes/_portal/memory'
import { Route as PortalModelsRouteImport } from './routes/_portal/models'
import { Route as PortalPoliciesRouteImport } from './routes/_portal/policies'
import { Route as PortalReleasesRouteImport } from './routes/_portal/releases'
import { Route as PortalSkillsRouteImport } from './routes/_portal/skills'
import { Route as PortalToolsRouteImport } from './routes/_portal/tools'
import { Route as PortalWorkRouteImport } from './routes/_portal/work'
import { Route as PortalTasksIndexRouteImport } from './routes/_portal/tasks/index'
import { Route as PortalTasksTaskIdRouteImport } from './routes/_portal/tasks/$taskId'

const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApprovalsRoute = PortalApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAuditRoute = PortalAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBackfillsRoute = PortalBackfillsRouteImport.update({
  id: '/backfills',
  path: '/backfills',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCostRoute = PortalCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEvalsRoute = PortalEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHealthRoute = PortalHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMemoryRoute = PortalMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => PortalRoute,
} as any)
const PortalModelsRoute = PortalModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPoliciesRoute = PortalPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReleasesRoute = PortalReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSkillsRoute = PortalSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => PortalRoute,
} as any)
const PortalToolsRoute = PortalToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWorkRoute = PortalWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTasksIndexRoute = PortalTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTasksTaskIdRoute = PortalTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/approvals': typeof PortalApprovalsRoute
  '/audit': typeof PortalAuditRoute
  '/backfills': typeof PortalBackfillsRoute
  '/cost': typeof PortalCostRoute
  '/evals': typeof PortalEvalsRoute
  '/health': typeof PortalHealthRoute
  '/memory': typeof PortalMemoryRoute
  '/models': typeof PortalModelsRoute
  '/policies': typeof PortalPoliciesRoute
  '/releases': typeof PortalReleasesRoute
  '/skills': typeof PortalSkillsRoute
  '/tools': typeof PortalToolsRoute
  '/work': typeof PortalWorkRoute
  '/tasks/$taskId': typeof PortalTasksTaskIdRoute
  '/tasks/': typeof PortalTasksIndexRoute
}
export interface FileRoutesByTo {
  '/approvals': typeof PortalApprovalsRoute
  '/audit': typeof PortalAuditRoute
  '/backfills': typeof PortalBackfillsRoute
  '/cost': typeof PortalCostRoute
  '/evals': typeof PortalEvalsRoute
  '/health': typeof PortalHealthRoute
  '/memory': typeof PortalMemoryRoute
  '/models': typeof PortalModelsRoute
  '/policies': typeof PortalPoliciesRoute
  '/releases': typeof PortalReleasesRoute
  '/skills': typeof PortalSkillsRoute
  '/tools': typeof PortalToolsRoute
  '/work': typeof PortalWorkRoute
  '/': typeof PortalIndexRoute
  '/tasks/$taskId': typeof PortalTasksTaskIdRoute
  '/tasks': typeof PortalTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/_portal/approvals': typeof PortalApprovalsRoute
  '/_portal/audit': typeof PortalAuditRoute
  '/_portal/backfills': typeof PortalBackfillsRoute
  '/_portal/cost': typeof PortalCostRoute
  '/_portal/evals': typeof PortalEvalsRoute
  '/_portal/health': typeof PortalHealthRoute
  '/_portal/memory': typeof PortalMemoryRoute
  '/_portal/models': typeof PortalModelsRoute
  '/_portal/policies': typeof PortalPoliciesRoute
  '/_portal/releases': typeof PortalReleasesRoute
  '/_portal/skills': typeof PortalSkillsRoute
  '/_portal/tools': typeof PortalToolsRoute
  '/_portal/work': typeof PortalWorkRoute
  '/_portal/': typeof PortalIndexRoute
  '/_portal/tasks/$taskId': typeof PortalTasksTaskIdRoute
  '/_portal/tasks/': typeof PortalTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/backfills'
    | '/cost'
    | '/evals'
    | '/health'
    | '/memory'
    | '/models'
    | '/policies'
    | '/releases'
    | '/skills'
    | '/tools'
    | '/work'
    | '/tasks/$taskId'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/approvals'
    | '/audit'
    | '/backfills'
    | '/cost'
    | '/evals'
    | '/health'
    | '/memory'
    | '/models'
    | '/policies'
    | '/releases'
    | '/skills'
    | '/tools'
    | '/work'
    | '/'
    | '/tasks/$taskId'
    | '/tasks'
  id:
    | '__root__'
    | '/_portal'
    | '/_portal/approvals'
    | '/_portal/audit'
    | '/_portal/backfills'
    | '/_portal/cost'
    | '/_portal/evals'
    | '/_portal/health'
    | '/_portal/memory'
    | '/_portal/models'
    | '/_portal/policies'
    | '/_portal/releases'
    | '/_portal/skills'
    | '/_portal/tools'
    | '/_portal/work'
    | '/_portal/'
    | '/_portal/tasks/$taskId'
    | '/_portal/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/approvals': {
      id: '/_portal/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof PortalApprovalsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/audit': {
      id: '/_portal/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof PortalAuditRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/backfills': {
      id: '/_portal/backfills'
      path: '/backfills'
      fullPath: '/backfills'
      preLoaderRoute: typeof PortalBackfillsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/cost': {
      id: '/_portal/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof PortalCostRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/evals': {
      id: '/_portal/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof PortalEvalsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/health': {
      id: '/_portal/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof PortalHealthRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/memory': {
      id: '/_portal/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof PortalMemoryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/models': {
      id: '/_portal/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof PortalModelsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/policies': {
      id: '/_portal/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PortalPoliciesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/releases': {
      id: '/_portal/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof PortalReleasesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/skills': {
      id: '/_portal/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof PortalSkillsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/tools': {
      id: '/_portal/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof PortalToolsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/work': {
      id: '/_portal/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof PortalWorkRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/tasks/': {
      id: '/_portal/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof PortalTasksIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/tasks/$taskId': {
      id: '/_portal/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof PortalTasksTaskIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalApprovalsRoute: typeof PortalApprovalsRoute
  PortalAuditRoute: typeof PortalAuditRoute
  PortalBackfillsRoute: typeof PortalBackfillsRoute
  PortalCostRoute: typeof PortalCostRoute
  PortalEvalsRoute: typeof PortalEvalsRoute
  PortalHealthRoute: typeof PortalHealthRoute
  PortalMemoryRoute: typeof PortalMemoryRoute
  PortalModelsRoute: typeof PortalModelsRoute
  PortalPoliciesRoute: typeof PortalPoliciesRoute
  PortalReleasesRoute: typeof PortalReleasesRoute
  PortalSkillsRoute: typeof PortalSkillsRoute
  PortalToolsRoute: typeof PortalToolsRoute
  PortalWorkRoute: typeof PortalWorkRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalTasksTaskIdRoute: typeof PortalTasksTaskIdRoute
  PortalTasksIndexRoute: typeof PortalTasksIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalApprovalsRoute: PortalApprovalsRoute,
  PortalAuditRoute: PortalAuditRoute,
  PortalBackfillsRoute: PortalBackfillsRoute,
  PortalCostRoute: PortalCostRoute,
  PortalEvalsRoute: PortalEvalsRoute,
  PortalHealthRoute: PortalHealthRoute,
  PortalMemoryRoute: PortalMemoryRoute,
  PortalModelsRoute: PortalModelsRoute,
  PortalPoliciesRoute: PortalPoliciesRoute,
  PortalReleasesRoute: PortalReleasesRoute,
  PortalSkillsRoute: PortalSkillsRoute,
  PortalToolsRoute: PortalToolsRoute,
  PortalWorkRoute: PortalWorkRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalTasksTaskIdRoute: PortalTasksTaskIdRoute,
  PortalTasksIndexRoute: PortalTasksIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
